#define NUMERO_INSUFICIENTE_DE_PARAMETROS 1

#define CARACTER_DE_ENTRADA_INVALIDO 2

#define INDICE_INVALIDO 3

#define CARACTER_NO_NUMERICO 4

#define CONFIGURACION_IMPOSIBLE_TABLERO_ENCHUFES 5

#define NUMERO_INCORRECTO_DE_PARAMETROS_TABLERO_ENCHUFES 6

#define MAPEO_ROTOR_INVALIDO 7

#define NO_POSICION_INICIAL_ROTOR 8

#define MAPEO_REFLECTOR_INVALIDO 9

#define NUMERO_INCORRECTO_DE_PARAMETROS_REFLECTOR 10

#define ERROR_ABRIR_ARCHIVO_DE_CONFIGURACION 11

#define SIN_ERROR 0